[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "torbot"
version = "4.3.0"
authors = [
    { name="Akeem King", email="akeemtlking@gmail.com" },
    { name="PS Narayanan", email="thepsnarayanan@gmail.com" },
]
description = "TorBot is an OSINT tool for the dark web."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Operating System :: OS Independent",
]
dependencies = [
  "altgraph>=0.17.4",
  "beautifulsoup4>=4.12.3",
  "certifi>=2024.7.4",
  "charset-normalizer>=3.3.2",
  "decorator>=5.1.1",
  "idna>=3.15",
  "igraph>=0.11.4",
  "joblib>=1.4.2",
  "macholib>=1.16.3",
  "progress>=1.6",
  "pyinstaller>=6.8.0",
  "pyinstaller-hooks-contrib>=2024.6",
  "PySocks>=1.7.1",
  "python-dotenv>=1.2.2",
  "scikit-learn>=1.5.0",
  "scipy>=1.13.0",
  "six>=1.16.0",
  "soupsieve>=2.8.4",
  "termcolor>=2.4.0",
  "texttable>=1.7.0",
  "threadpoolctl>=3.5.0",
  "tomli>=2.0.1; python_version < '3.11'",
  "urllib3>=2.7.0",
  "validators>=0.22.0",
  "treelib>=1.7.1",
  "numpy>=1.26.4",
  "unipath>=1.1",
  "httpx[socks]>=0.27.0",
  "tabulate>=0.9.0",
  "phonenumbers>=8.13.37",
  "pytest>=9.0.3",
  "yattag>=1.15.2",
]

[project.scripts]
torbot = "torbot.cli:main"
